name: "🆕 New Extension"
description: "Submit a new extension to the GNOME Beta Store"
title: "[Extension] New: <Extension Name>"
labels: ["nueva-extension"]
body:
  - type: markdown
    attributes:
      value: "Welcome! Use this form to register a new extension. For files, simply drag and drop them."
  - type: input
    id: uuid
    attributes:
      label: "Extension UUID"
      description: "e.g., my-extension@author.com"
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: "Clear Name"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
    validations:
      required: true
  - type: input
    id: github_url
    attributes:
      label: "GitHub Link"
    validations:
      required: true
  - type: input
    id: promo_url
    attributes:
      label: "Website / Promo Link"
    validations:
      required: false
  - type: textarea
    id: zip_file
    attributes:
      label: "ZIP File"
    validations:
      required: true
  - type: textarea
    id: icon_file
    attributes:
      label: "Icon (icon.png)"
    validations:
      required: true
  - type: textarea
    id: demo_files
    attributes:
      label: "Screenshots"
    validations:
      required: true
